### ISSUE TITLE
SyncThing web GUI

### ISSUE THREAD

**Issue by kibernaut** [cmars/oniongrok#8]
Great project, thanks.

Doesn't work with WEB GUI Syncthing (8384) - "Host check error". However, python -m http.server works as it should.

Client site - Win10 + TorBrowser. Second site - Ubuntu 20.04.

**Comment by cmars** [comment]
Giving this a bit more thought, I'd consider waiting for client auth support to land before using oniongrok to forward a Syncthing admin UI. Sounds like something you'd want to restrict access to.

**Comment by cmars** [comment]
I'm going to close this, as I'm not sure there's anything wrong on the oniongrok side. It's going to depend on how that Syncthing SPA works. If you can find the other ports it's trying to connect to, perhaps forwarding all of them to the same onion will work.

Again though, be careful that you're not exposing your Syncthing instance in ways you really shouldn't. If it were me, I'd wait for client auth to do this, it will likely come out in the next 0.4.0 release.
